import { jsPDF } from 'jspdf'
import { autoTable } from 'jspdf-autotable'
import html2canvas from 'html2canvas'
import type { RiskReport, RiskSeverity } from '@/types'

const PAGE_WIDTH_MM = 210
const PAGE_HEIGHT_MM = 297
const MARGIN_MM = 15
const CONTENT_WIDTH_MM = PAGE_WIDTH_MM - MARGIN_MM * 2

const SEVERITY_FILL: Record<RiskSeverity, [number, number, number]> = {
  Critical: [254, 202, 202],
  High:     [254, 215, 170],
  Medium:   [254, 240, 138],
  Low:      [187, 247, 208],
  Unscored: [229, 231, 235],
}

function formatDateTime(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  return `${d.toLocaleDateString()} ${d.toLocaleTimeString()}`
}

function todayDateStr(): string {
  return new Date().toISOString().split('T')[0]
}

async function captureElement(
  el: HTMLElement,
): Promise<{ dataUrl: string; widthMm: number; heightMm: number }> {
  const canvas = await html2canvas(el, { backgroundColor: '#ffffff', scale: 2 })
  const dataUrl = canvas.toDataURL('image/png')
  const aspect = canvas.height / canvas.width
  const widthMm = CONTENT_WIDTH_MM
  const heightMm = widthMm * aspect
  return { dataUrl, widthMm, heightMm }
}

function ensureSpace(doc: jsPDF, cursorY: number, needed: number): number {
  if (cursorY + needed > PAGE_HEIGHT_MM - MARGIN_MM) {
    doc.addPage()
    return MARGIN_MM
  }
  return cursorY
}

function drawFooter(doc: jsPDF): void {
  const total = doc.getNumberOfPages()
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    doc.setFontSize(9)
    doc.setTextColor(120)
    doc.text('Firewatch', MARGIN_MM, PAGE_HEIGHT_MM - 8)
    doc.text(
      `Page ${i} of ${total}`,
      PAGE_WIDTH_MM - MARGIN_MM,
      PAGE_HEIGHT_MM - 8,
      { align: 'right' },
    )
    doc.setTextColor(0)
  }
}

function triggerPdfDownload(doc: jsPDF, filename: string): void {
  const blob = doc.output('blob')
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

export async function generateRiskReportPdf(
  data: RiskReport,
  options: { matrixEl: HTMLElement | null; chartEl: HTMLElement | null },
): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  let y = MARGIN_MM

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text('Firewatch Risk Report', MARGIN_MM, y)
  y += 9

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text(`From ${data.date_range.start} to ${data.date_range.end}`, MARGIN_MM, y)
  y += 6

  const author = data.generated_by.full_name || data.generated_by.email
  doc.setFontSize(10)
  doc.setTextColor(80)
  doc.text(`Generated by ${author} (${data.generated_by.role})`, MARGIN_MM, y)
  y += 5
  doc.text(`Generated at ${formatDateTime(data.generated_at)}`, MARGIN_MM, y)
  y += 9
  doc.setTextColor(0)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('Summary', MARGIN_MM, y)
  y += 6

  const s = data.summary
  const summaryRows: Array<[string, string]> = [
    ['Total Risks', String(s.total)],
    ['Open', String(s.by_status['open'] ?? 0)],
    ['In Progress', String(s.by_status['in_progress'] ?? 0)],
    ['Mitigated', String(s.by_status['mitigated'] ?? 0)],
    ['Accepted', String(s.by_status['accepted'] ?? 0)],
    ['Closed', String(s.by_status['closed'] ?? 0)],
    ['Overdue Responses', String(s.overdue_responses)],
    ['Overdue Reviews', String(s.overdue_reviews)],
  ]

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  for (const [label, value] of summaryRows) {
    y = ensureSpace(doc, y, 6)
    doc.setTextColor(80)
    doc.text(label, MARGIN_MM, y)
    doc.setTextColor(0)
    doc.text(value, MARGIN_MM + 70, y)
    y += 6
  }
  y += 4

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('Risk Matrix', MARGIN_MM, y)
  y += 6
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)

  if (options.matrixEl) {
    try {
      const { dataUrl, widthMm, heightMm } = await captureElement(options.matrixEl)
      const cappedHeight = Math.min(heightMm, PAGE_HEIGHT_MM - MARGIN_MM - y)
      const cappedWidth = widthMm * (cappedHeight / heightMm)
      y = ensureSpace(doc, y, cappedHeight)
      doc.addImage(dataUrl, 'PNG', MARGIN_MM, y, cappedWidth, cappedHeight)
      y += cappedHeight + 6
    } catch {
      doc.setTextColor(120)
      doc.text('Risk matrix unavailable.', MARGIN_MM, y)
      doc.setTextColor(0)
      y += 6
    }
  } else {
    doc.setTextColor(120)
    doc.text('Risk matrix unavailable.', MARGIN_MM, y)
    doc.setTextColor(0)
    y += 6
  }

  y = ensureSpace(doc, y, 12)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('Average Risk Score Over Time', MARGIN_MM, y)
  y += 6
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)

  if (data.score_history.points.length === 0) {
    doc.setTextColor(120)
    doc.text('No assessments recorded in this date range.', MARGIN_MM, y)
    doc.setTextColor(0)
    y += 6
  } else if (options.chartEl) {
    try {
      const { dataUrl, widthMm, heightMm } = await captureElement(options.chartEl)
      const cappedHeight = Math.min(heightMm, PAGE_HEIGHT_MM - MARGIN_MM - y)
      const cappedWidth = widthMm * (cappedHeight / heightMm)
      y = ensureSpace(doc, y, cappedHeight)
      doc.addImage(dataUrl, 'PNG', MARGIN_MM, y, cappedWidth, cappedHeight)
      y += cappedHeight + 6
    } catch {
      doc.setTextColor(120)
      doc.text('Chart unavailable.', MARGIN_MM, y)
      doc.setTextColor(0)
      y += 6
    }
  } else {
    doc.setTextColor(120)
    doc.text('Chart unavailable.', MARGIN_MM, y)
    doc.setTextColor(0)
    y += 6
  }

  if (data.risks && data.risks.length > 0) {
    doc.addPage()
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.text('Risk Register', MARGIN_MM, MARGIN_MM)

    autoTable(doc, {
      startY: MARGIN_MM + 6,
      margin: { left: MARGIN_MM, right: MARGIN_MM, bottom: MARGIN_MM + 6 },
      head: [['ID', 'Title', 'Category', 'Status', 'Severity', 'Score', 'Owner', 'Next Review']],
      body: data.risks.map((r) => [
        String(r.id),
        r.title,
        r.category ?? '',
        r.status,
        r.severity,
        r.current_score === null ? '' : String(r.current_score),
        r.owner_name ?? '',
        r.next_review_date ?? '',
      ]),
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2, overflow: 'linebreak' },
      headStyles: { fillColor: [55, 65, 81], textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 12 },
        1: { cellWidth: 45 },
        2: { cellWidth: 22 },
        3: { cellWidth: 22 },
        4: { cellWidth: 18 },
        5: { cellWidth: 12, halign: 'right' },
        6: { cellWidth: 25 },
        7: { cellWidth: 24 },
      },
      didParseCell: (cell) => {
        if (cell.section === 'body' && cell.column.index === 4) {
          const sev = String(cell.cell.raw) as RiskSeverity
          const fill = SEVERITY_FILL[sev]
          if (fill) cell.cell.styles.fillColor = fill
        }
      },
    })
  } else if (data.risks && data.risks.length === 0) {
    y = ensureSpace(doc, y, 12)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.text('Risk Register', MARGIN_MM, y)
    y += 6
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(120)
    doc.text('No risks in this report.', MARGIN_MM, y)
    doc.setTextColor(0)
  }

  drawFooter(doc)
  triggerPdfDownload(doc, `firewatch-risk-report-${todayDateStr()}.pdf`)
}
