"""add control framework mapping tables

Revision ID: 3f5a921133a6
Revises: b8e62d2cace1
Create Date: 2026-05-29 13:25:03.359941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '3f5a921133a6'
down_revision: Union[str, None] = 'b8e62d2cace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_frameworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['control_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id', 'control_id', name='uq_controls_framework_control')
    )
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controls_framework_id'), ['framework_id'], unique=False)

    op.create_table('risk_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_id', 'control_id', name='uq_risk_controls_risk_control')
    )
    with op.batch_alter_table('risk_controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_controls_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_controls_risk_id'), ['risk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_controls_risk_id'))
        batch_op.drop_index(batch_op.f('ix_risk_controls_control_id'))

    op.drop_table('risk_controls')
    with op.batch_alter_table('controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controls_framework_id'))

    op.drop_table('controls')
    op.drop_table('control_frameworks')
    # ### end Alembic commands ###
