// Flat-config ESLint setup for the Firewatch frontend.
//
// This is ADVISORY ONLY: it is intentionally NOT wired into `npm run build`.
// Run it via `npm run lint` (or `npm run lint:fix`). It uses the TYPE-CHECKED
// typescript-eslint preset so rules like `no-floating-promises` have real type
// information to work with.

import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'

export default tseslint.config(
  {
    // Never lint build output, deps, coverage, or the auto-generated OpenAPI
    // types file (regenerated by `npm run generate:types`).
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      'src/types/generated.ts',
    ],
  },

  // Base JS + type-checked TS recommendations. We include `stylisticTypeChecked`
  // as well; the few noisy rules it brings are down-ranked individually below.
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  // Type-aware parser setup for everything we lint.
  {
    languageOptions: {
      parserOptions: {
        // Modern typescript-eslint project service: resolves the right tsconfig
        // per file (src -> tsconfig.json, config files -> tsconfig.node.json).
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // Application source: browser environment + React rules.
  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      ...reactHooks.configs['recommended-latest'].rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],

      // tsc already enforces noUnusedLocals/noUnusedParameters, so keep this as
      // a warning (with _-prefixed args ignored) to avoid duplicate red errors.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // React event handlers are routinely `onClick={async () => ...}`; the
      // strict reading of no-misused-promises flags every one of these. Allow
      // promise-returning functions in void-attribute positions while still
      // catching genuinely misused promises (e.g. in conditionals).
      '@typescript-eslint/no-misused-promises': [
        'error',
        { checksVoidReturn: { attributes: false } },
      ],

      // Stylistic/noisy-but-not-a-bug rules from the type-checked presets.
      // Down-ranked to warnings so the command stays green and signal stays high.
      '@typescript-eslint/no-explicit-any': 'warn', // a few intentional escape hatches
      '@typescript-eslint/restrict-template-expressions': 'warn', // numbers/booleans in templates are fine
      '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
      '@typescript-eslint/prefer-nullish-coalescing': 'warn', // ?? migration is gradual, not urgent
      '@typescript-eslint/prefer-optional-chain': 'warn',
      '@typescript-eslint/consistent-type-definitions': 'off', // interface vs type is a team-preference, not a bug
      '@typescript-eslint/consistent-indexed-object-style': 'warn',
      '@typescript-eslint/array-type': 'warn', // T[] vs Array<T> is cosmetic
      '@typescript-eslint/dot-notation': 'warn',
      '@typescript-eslint/no-empty-function': 'warn', // no-op callbacks/mocks are legitimate

      // `import.meta.env.*` is typed `any` by Vite, and FastAPI error bodies are
      // narrowed at the use-site; the residual unsafe-* hits are not real bugs.
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-base-to-string': 'warn',
      '@typescript-eslint/require-await': 'warn',

      // react-hooks v7 ships new React-Compiler-style correctness rules
      // (set-state-in-effect, refs, purity). They flag many established,
      // intentional patterns in this codebase (e.g. async-fetch-then-setState in
      // effects, reading ref.current to pass DOM nodes to an export helper).
      // Keep them as warnings: useful signal without blocking the lint gate.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/purity': 'warn',
    },
  },

  // Test files: relax type-checked rules that are noisy in tests.
  {
    files: ['src/**/*.test.{ts,tsx}', 'src/**/__tests__/**', 'src/test/**'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/unbound-method': 'off',
      // Tests cast DOM query results (e.g. `as HTMLInputElement`) to reach
      // `.value`/`.checked`. Those casts are NOT redundant for tsc, so do not
      // let --fix strip them — turn the rule off for tests.
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-empty-function': 'off',
    },
  },

  // TS config files (vite/vitest): node environment. These are type-checked
  // against tsconfig.node.json, which does not enable strictNullChecks, so the
  // nullish-coalescing rule can't run there — turn it off for these files only.
  {
    files: ['vite.config.ts', 'vitest.config.ts'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
    },
  },

  // Plain-JS config files (eslint.config.js, tailwind/postcss configs) are not
  // part of any tsconfig `include`, so type-aware linting can't resolve them.
  // Lint them with node globals but WITHOUT type information.
  {
    files: ['**/*.js'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
)
